#!/usr/bin/env node
"use strict";

const sshpk = require('sshpk');
const fs = require('fs');
const os = require('os');
const io = require('socket.io-client');
const ros = require('rosnodejs');
const geometry_msgs = ros.require('geometry_msgs');

const remoteConfig = {
  "name": "ganymede",
  "ui": {
    "fixed": [
       {
         "type": "stick",
         "id": "stick0",
         "aspectRatio": 1.0,
       }
    ]
  }
}

// ssh

let publicKeyText = fs.readFileSync(os.homedir() + '/.ssh/id_rsa.pub');
let privateKeyText = fs.readFileSync(os.homedir() + '/.ssh/id_rsa');
let publicKey = sshpk.parseKey(publicKeyText, 'ssh');
let privateKey = sshpk.parsePrivateKey(privateKeyText, 'ssh');

// ros init
ros.initNode('remote_node').then(() => {
  console.log("ros node initialized")
});
const nh = ros.nh;

// subscribers

const sub = nh.subscribe('/rosout', 'rosgraph_msgs/Log', (msg) => {
  socket.emit('rosout', msg);
});

// publishers

const pub_motion = nh.advertise('/motion/level2', 'geometry_msgs/Twist')

// socket.io

var socket = io('https://robot.dheera.net/robot');

socket.on('connect', () => {
  console.log('connect');

  socket.emit('auth_fingerprint', publicKey.fingerprint().toString());
});

socket.on('auth_verify', (msg, callback) => {
  console.log('auth_verify', msg);
  if(!msg.data) {
    console.log('did not receive data to sign');
    return;
  }

  let s = privateKey.createSign('sha256');
  s.update(msg.data);
  let signature = s.sign();
  callback({signature: signature.toString(), type: signature.type});
});

socket.on('e', (data) => {
  console.log('e', data);
  if(data[0] === "stick0") onStick(data[1]);
});

socket.on('auth_status', (status) => {
  console.log('auth_status', status);
  socket.emit('remote_config', remoteConfig);
});

socket.on('disconnect', () => {
  console.log('disconnect');
});

function onStick(pos) {
  if(pos.length !== 2) return;
  if(!(typeof(pos[0]) === "number")) return;
  if(!(typeof(pos[1]) === "number")) return;

  let t = new geometry_msgs.msg.Twist();
  let x = pos[0];
  let y = pos[1];
  t.linear.x = -y/5;
  t.angular.z = -x;
  pub_motion.publish(t);
}
